Develop
HellInsider/SignalBigLab pull request #2
Opened 2022-04-12 22:45 UTC by HellInsider

2022-04-18 22:25 UTC, ArsenyVelichko reviewed
Желательно добавить результаты работы алгоритма.
Также стоит добавить комментарии к основным функциям алгоритма, так как понять, например, что метод rotate "выравнивает" OBB достаточно сложно.

2022-04-18 22:25 UTC, ArsenyVelichko commented on code/IntellijPlacer.py
> +        self.binarized_objects = [self.binarize(t) for t in self.pics]
Список бинаризованных объектов нигде не используется.

2022-04-18 22:25 UTC, ArsenyVelichko commented on code/IntellijPlacer.py
> +        thetas = np.rad2deg(thetas)
Не могли бы вы пояснить, почему здесь нельзя также использовать матрицу поворота, как и в шаге алгоритма упаковки?

2022-04-19 10:55 UTC, pikabol88 commented on README.md
> +- цвета предметов, присутствующих в кадре, должна быть контрастны относительно поверхности, на которой располагаются
опечатка

2022-04-19 11:03 UTC, pikabol88 commented on README.md
> +- No, в противном случае
Вывод в консоль не лучший вариант,  по исходным требованиям  “Intelligent Placer” должен быть оформлен в виде python-модуля, содержащим функцию - точку входа, которая возвращает True если предметы могут влезть в многоугольник, иначе False

2022-04-19 11:04 UTC, pikabol88 commented on README.md
> +Я строю алгоритм, который может найти решение для более общей задачи, это означает, что программа может работать с другим набором элементов с минимальными изменениями. Следовательно, я не буду исполь
опечатка в последнем предложении

2022-04-19 11:10 UTC, pikabol88 commented on README.md
> + 1.4 binary_fill_holes skimage.
лучше вместо названий добавить описание функциональности
Пример:
1.2 Поиск границ предметов с помощью детектора Кэнни

2022-04-19 11:12 UTC, pikabol88 commented on README.md
> +6.1 Если мколлизий между границами и объектами не выявлено, то переходим к следующему объекту (или сообщаем об успешном размещении, если это был последний объект).
опечатка

2022-04-19 11:13 UTC, pikabol88 commented on README.md
> +6.2 Иначе вращяем объект на 3 градуса, а затем смещаем тектуру объекта на значение, равное 5% от размера многоугольника по оси Х и У (вложенный цикл).
опечатка в слове "текстуру"

2022-04-19 11:14 UTC, pikabol88 commented on README.md
> +Тестировочный набор может быть найден [здесь](https://github.com/HellInsider/SignalBigLab/tree/develop/dataset)
Вероятно, **Тестовый** набор

2022-04-19 11:33 UTC, pikabol88 requested changes
Алгоритм достаточно подробно описан и понятен, но есть несколько пунктов, которые мешают назвать работу "завершенной" :

1. Необходимо исправить опечатки в требованиях и алгоритме. 
2. Более развернуто описать шаги в алгоритма, в которых на данный момент описаны только используемые функции. 
3. В коде содержится вывод в консоль, который, видимо, использовался для более удобной разработки автором. В конечном варианте алгоритма такого быть не должно
4. Хотелось бы видеть результаты работы алгоритма на ваших тестовых данных в репозитории

2022-04-20 20:59 UTC, OvechkinDanil commented on code/IntellijPlacer.py
> +    def get_pics(self, path, is_small=False):                # загрузка изображений
Добавлю к тому, что написал Арсений про неиспользуемый список бинаризованных изображений:
Этот метод использовался только для построение этого списка. Соответсвенно его тоже стоит удалить

2022-04-20 20:59 UTC, OvechkinDanil commented on code/IntellijPlacer.py
> +                    copy = np.ones(shape=(
Мне кажется, стоит отрефакторить этот момент, т.к. очень сложно читать код.
Я бы на твоем месте завел локальные переменные

2022-04-21 13:49 UTC, MekhailS reviewed
Много функций классов можно сделать статическими

2022-04-21 13:49 UTC, MekhailS commented on code/IntellijPlacer.py
> +    def rotate(self, cnt, angle, img_size):         # поворот текстуры
Комментарии на русском >_<

2022-04-21 13:49 UTC, MekhailS commented on code/IntellijPlacer.py
> +    def rotate(self, cnt, angle, img_size):         # поворот текстуры
JFYI, вращение можно заимплементить проще через вращение изображения с контуром (ndimage.rotate), + дальше ты как раз это изображение и строишь, так что накладок серьезных дополнительных не возникло бы

2022-04-21 13:51 UTC, MekhailS reviewed
Нет ipynb ноутбука 🙁, сложно понять, что происходит в целом

2022-04-21 14:11 UTC, MekhailS commented on code/IntellijPlacer.py
> +        counters_modified = []
Ниже тоже

2022-04-21 14:11 UTC, MekhailS commented on code/IntellijPlacer.py
> +        res_counters = np.zeros((self.img.shape[0], self.img.shape[1], 3), dtype=np.uint8)
Если дальше смотреть, то тут в следующем цикле как раз куча ненужного кода, работающего с этой переменной, который только мешает

2022-04-21 14:11 UTC, MekhailS commented on code/IntellijPlacer.py
> +        for rec in rects:
Опять же лучше без сокращений, читать было бы проще

2022-04-21 14:11 UTC, MekhailS commented on code/IntellijPlacer.py
> +                for half_trans_x in range(destination.shape[1] // 2):                       # перемещение по Х и У
Это можно переписать через `range` с шагом

2022-04-21 14:11 UTC, MekhailS commented on code/IntellijPlacer.py
> +        for el in main_poly.flat:
Это можно переписать как минимум на `np.count_nonzero(main_poly  == 255)`

2022-04-21 14:11 UTC, MekhailS commented on code/IntellijPlacer.py
> +            pics = [imageio.imread(path + "/small_res/" + fname) for fname in os.listdir(path + "/small_res") if
Захардкоженный путь`/small_res/`встречается 6 раз, лучше вынести в константу

2022-04-21 14:14 UTC, MekhailS reviewed
Было бы круто иметь визуализауцию результатов работы алгоритма, т.е. как уложил по итогу

2022-04-21 14:23 UTC, MekhailS commented
Еще коммит "Add files via upload" говорит о том, что ты закидываешь файлы в репу через сам гитхаб
Не солидно

Манипулировать с гитом можно например через IDE
И удобней в разы чем веб интерфейс гитхаба

2022-04-22 16:46 UTC, HellInsider commented on code/IntellijPlacer.py
> +        contours, hierarchy = cv.findContours(self.img, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)
Спасибо за совет. Применил.

2022-04-22 16:46 UTC, HellInsider commented on code/IntellijPlacer.py
> +        print(os.getcwd())
Да, это так. Вывод консоли нужен был мне для отладки. В новой версии ничего лишнего не выводится.

2022-04-22 16:46 UTC, HellInsider commented on code/IntellijPlacer.py
> +            print("No")
Сделал.

2022-04-22 16:46 UTC, HellInsider commented on code/IntellijPlacer.py
> +            pics = [t[0: t.shape[0] - 0, 0: t.shape[1] - 0] for t in pics]
Остались артефакты отладки. Убрал.

2022-04-22 16:46 UTC, HellInsider commented on code/IntellijPlacer.py
> +                if err_cnt > main_poly.shape[0] * main_poly.shape[1] / 5000:
Вычисление процентной составляющей ошибки. Исправлено.

2022-04-22 16:46 UTC, HellInsider commented on code/IntellijPlacer.py
> +        thetas = np.rad2deg(thetas)
В одном случае мы работаем с контурами, а в другом с матрицей.

2022-04-22 16:46 UTC, HellInsider commented on README.md
> +- цвета предметов, присутствующих в кадре, должна быть контрастны относительно поверхности, на которой располагаются
Исправлено.

2022-04-22 16:46 UTC, HellInsider commented on README.md
> +- No, в противном случае
Справедливо. Исправлено.

2022-04-22 16:46 UTC, HellInsider commented on README.md
> +Я строю алгоритм, который может найти решение для более общей задачи, это означает, что программа может работать с другим набором элементов с минимальными изменениями. Следовательно, я не буду исполь
Да. Исправлено.

2022-04-22 16:46 UTC, HellInsider commented on README.md
> + 1.4 binary_fill_holes skimage.
Выполнено.

2022-04-22 16:46 UTC, HellInsider commented on README.md
> +6.1 Если мколлизий между границами и объектами не выявлено, то переходим к следующему объекту (или сообщаем об успешном размещении, если это был последний объект).
И снова вы правы. Досадно.

2022-04-22 16:46 UTC, HellInsider commented on README.md
> +6.2 Иначе вращяем объект на 3 градуса, а затем смещаем тектуру объекта на значение, равное 5% от размера многоугольника по оси Х и У (вложенный цикл).
Исправлено.

2022-04-22 16:46 UTC, HellInsider commented on README.md
> +Тестировочный набор может быть найден [здесь](https://github.com/HellInsider/SignalBigLab/tree/develop/dataset)
Верно. Спасибо.

2022-04-22 16:46 UTC, HellInsider commented on README.md
> +- поверхность должна быть достаточного размера, чтобы предметы на ней помещались целиком и не свисали их отдельные части
Я тоже не могу вспомнить, что имел в виду. Исправил.

2022-04-22 16:46 UTC, HellInsider commented on README.md
> +- каждый из выбранных предметов на фоне белого листа бумаги А4 должен попадать на фотографию целиком, так чтобы углы и края листа были видны и не перекрывались
Здесь речь идет о предметах. Предметы не должны перекрывать края листа, так как я не уверен, что программа в этом случае будет работать правильно. 
Добавил слово "предметами" в конец предложения.

2022-04-22 16:46 UTC, HellInsider commented on README.md
> +4.2 Если предыдущее условие выполняется, выводим сообщение о провале. Иначе следуем дальше.
False.

2022-04-22 16:46 UTC, HellInsider commented on code/IntellijPlacer.py
> +    def to_pol(self, x, y):
Исправил.

2022-04-22 16:46 UTC, HellInsider commented on code/IntellijPlacer.py
> +    def get_pics(self, path, is_small=False):                # загрузка изображений
Бинаризованные изображения необходимы для поиска контуров. 
Все лишнее, про что было сказано, убрал.

2022-04-22 16:46 UTC, HellInsider commented on code/IntellijPlacer.py
> +                    copy = np.ones(shape=(
Локальные переменные не ввел, но более читаемым код сделал.

2022-04-22 16:47 UTC, HellInsider commented on code/IntellijPlacer.py
> +    def rotate(self, cnt, angle, img_size):         # поворот текстуры
Спасибо за ценный совет. Пусть это будет одним из малочисленных случаев, когда код останется неизменным.

2022-04-22 16:47 UTC, HellInsider commented on code/IntellijPlacer.py
> +            pics = [imageio.imread(path + "/small_res/" + fname) for fname in os.listdir(path + "/small_res") if
Незамеченный мной пережиток отладки. Спасибо, исправил.

2022-04-22 16:47 UTC, HellInsider commented on code/IntellijPlacer.py
> +                    trans_x = 2 * half_trans_x
Исправил.

2022-04-22 16:47 UTC, HellInsider commented on code/IntellijPlacer.py
> +    def to_cart(self, theta, rho):
Справедливо. Исправил.

2022-04-22 16:47 UTC, HellInsider commented on code/IntellijPlacer.py
> +        counters_modified = []
Спасибо. Исправил.

2022-04-22 16:47 UTC, HellInsider commented on code/IntellijPlacer.py
> +        res_counters = np.zeros((self.img.shape[0], self.img.shape[1], 3), dtype=np.uint8)
Нужен был для отладки и вывода на экран промежуточных результатов. Убрал.

2022-04-22 16:47 UTC, HellInsider commented on code/IntellijPlacer.py
> +        for rec in rects:
Пусть это и незначительно, но изменил.

2022-04-22 16:47 UTC, HellInsider commented on code/IntellijPlacer.py
> +                for half_trans_x in range(destination.shape[1] // 2):                       # перемещение по Х и У
Выполнено.

2022-04-22 16:47 UTC, HellInsider commented on code/IntellijPlacer.py
> +        for el in main_poly.flat:
Спасибо за совет. Но там должно быть не ==, а >.  Исправил.

2022-04-22 16:47 UTC, HellInsider commented on code/IntellijPlacer.py
> +            pics = [imageio.imread(path + "/small_res/" + fname) for fname in os.listdir(path + "/small_res") if
Complete.

2022-04-22 16:47 UTC, HellInsider commented on code/IntellijPlacer.py
> +import os
Впервые вижу аббревиатуру PEP8 и не считаю себя хорошим программистом на питоне. Поэтому, позволю себе не следовать этому стандарту)

2022-04-22 16:47 UTC, HellInsider commented on README.md
> +6.2 Иначе вращяем объект на 3 градуса, а затем смещаем тектуру объекта на значение, равное 5% от размера многоугольника по оси Х и У (вложенный цикл).
Мое упущение. Мы сначала вращаем, потом сдвигаем, пока не дойдем до конца, либо пока не сможем поместить предмет. В первом случае возвращаемся и вращаем еще на 1 шаг.  Дописал в файле.

2022-04-22 16:56 UTC, MekhailS commented on README.md
> +6.2 Иначе вращяем объект на 3 градуса, а затем смещаем тектуру объекта на значение, равное 5% от размера многоугольника по оси Х и У (вложенный цикл).
А, все, понял
Я у себя просто двигаю, и на каждой позиции вращаю, а ты делаешь в обратном порядке)

2022-04-22 17:07 UTC, merged